const ROLES = Object.freeze({
  USER: 'USER',
  AGENT: 'AGENT',
  ADMIN: 'ADMIN'
});

const STATUSES = Object.freeze({
  OPEN: 'OPEN',
  ASSIGNED: 'ASSIGNED',
  IN_PROGRESS: 'IN_PROGRESS',
  WAITING_USER: 'WAITING_USER',
  RESOLVED: 'RESOLVED',
  CLOSED: 'CLOSED',
  REJECTED: 'REJECTED'
});

const PRIORITIES = Object.freeze({
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
});

const ACTIVE_STATUSES = [STATUSES.OPEN, STATUSES.ASSIGNED, STATUSES.IN_PROGRESS, STATUSES.WAITING_USER];

module.exports = { ROLES, STATUSES, PRIORITIES, ACTIVE_STATUSES };
